# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#

CongressApi.new.get_members(117,'senate')
CongressApi.new.get_members(116,'senate')
# CongressApi.new.get_members(115,'senate')
# CongressApi.new.get_members(114,'senate')
# CongressApi.new.get_members(113,'senate')
# CongressApi.new.get_members(112,'senate')
# CongressApi.new.get_members(111,'senate')
# CongressApi.new.get_members(110,'senate')
# CongressApi.new.get_members(109,'senate')
# CongressApi.new.get_members(108,'senate')
# CongressApi.new.get_members(107,'senate')
# CongressApi.new.get_members(106,'senate')
# CongressApi.new.get_members(105,'senate')
# CongressApi.new.get_members(104,'senate')
# CongressApi.new.get_members(103,'senate')
# CongressApi.new.get_members(102,'senate')
# CongressApi.new.get_members(101,'senate')
# CongressApi.new.get_members(100,'senate')

CongressApi.new.get_members(117,'house')
CongressApi.new.get_members(116,'house')
# CongressApi.new.get_members(115,'house')
# CongressApi.new.get_members(114,'house')
# CongressApi.new.get_members(113,'house')
# CongressApi.new.get_members(112,'house')
# CongressApi.new.get_members(111,'house')
# CongressApi.new.get_members(110,'house')
# CongressApi.new.get_members(109,'house')
# CongressApi.new.get_members(108,'house')
# CongressApi.new.get_members(107,'house')
# CongressApi.new.get_members(106,'house')
# CongressApi.new.get_members(105,'house')
# CongressApi.new.get_members(104,'house')
# CongressApi.new.get_members(103,'house')
# CongressApi.new.get_members(102,'house')

